### ISSUE TITLE
Confusing calendar instructions regarding oauth credentials

### ISSUE THREAD

**Issue by russellsilva** [google/google-api-ruby-client-samples#10]
The [Calendar demo readme](https://github.com/google/google-api-ruby-client-samples/tree/master/calendar) contains the following instructions:

> Edit the calendar.rb file and enter the values for the following properties that you retrieved from the API Console:
> 
> oauth_client_id
> oauth_client_secret

I'm confused by these instructions because the strings `oauth_client_id` and `oauth_client_secret` [never appear in calendar.rb](https://github.com/google/google-api-ruby-client-samples/blob/master/calendar/calendar.rb). What am I missing here?

**Comment by endlos** [comment]
Thanks @tryceattack
