### ISSUE TITLE
:application_name and :application_version when initializing the client

### ISSUE THREAD

**Issue by jmazin** [google/google-api-ruby-client-samples#12]
Hi!

Thanks for the hard work.  I get this warning using the 'googleplus' example:
`WARN -- : Google::APIClient - Please provide :application_name and :application_version when initializing the client`.

Was wondering if there's something we're not doing.  Thanks.

**Comment by niaomingjian** [comment]
Help!
What the PRODUCT NAME shoud be?

**Comment by deepak** [comment]
@niaomingjian product name is whatever you set it. 
will show in the consent page when the user is asked for permissions 
it is the `application_name`

`application_version` is the version of the client
according to the code, it is set as '0.0.0.0' by default

this warning is shown only when `application_name` is not given
