### ISSUE TITLE
How to access calendar?

### ISSUE THREAD

**Issue by firedev** [google/google-api-ruby-client-samples#32]
Sorry I am a bit frustrated after spending the whole day trying to get the entries from public calendar feed. It should be trivial but due to absence of V2 API docs I had to abandon a working implementation of XML calendar feed parser and now I am here.

I don't understand how to get access to the calendar. There is no `"Registered apps"` nor `"REGISTER APP"`, no `"Web application" for the "Platform"`.

All I need is to get a handful of upcoming events from a public calendar. Should be easy right?

**Comment by endlos** [comment]
I feel your pain @firedev. 
The README says there are 2 options: Old G.dev and New G.dev, but none are accurate. So just find the way to create a "New credential" with "OAuth client ID" so you can get a JSON file which you need to rename exactly to client_secrets.json and put it in the sample folder. Then "bundle", then start sinatra: "bundle exec ruby calendar.rb".

Notice this is for google-api-client v0.8, as the 0.9 Alpha uses a very different syntax.

Hope this helps someone :-)
