### ISSUE TITLE
Any chance of an example that works with the 0.9 ruby library?

### ISSUE THREAD

**Issue by Carpela** [google/google-api-ruby-client-samples#42]
Specifically looking for an example of authentication with a service account (for gmail would be lovely).

**Comment by evinsou** [comment]
I am not from a developer team. Just a common ruby dev. 
I doubt in it. Because of difference in folder structure.

**Comment by malovme** [comment]
Samples for 0.9 are [here](https://github.com/google/google-api-ruby-client/tree/master/samples)
